### PR TITLE
Really fixed the bug

### PR DESCRIPTION
**Pull request by KyleFiala**
my bad again

### CODE REVIEW

**Comment by MoonWolf125** [comment]
I know this is a really cool feature, but you need to stop adding bugs. That or use the feature branch!

**Comment by alunduil** [comment]
I usually use git flow in something that requires a few synchronization points.  If anyone is interested in seeing how I use it for a blog, let me know.

**Comment by MoonWolf125** [comment]
@alunduil I'd enjoy the opportunity to see it in the blog context. These comments and issues are for the Git Workshop currently ongoing at MSUM. We had about 15 people show up today, I'm expecting mroe tomorrow as most CSIS classes are MWF this Semester. Thanks!

**Comment by alunduil** [comment]
@MoonWolf125 alright, so I keep getting notified of all of these issues and I'm sure others do as well.  Is it part of the workshop for issues like this to be filed?  I can unsubscribe from this project but do want to help if I can.  

I'm suggesting CI because of the issues and pull requests I see being submitted.  If bugs are quickly found and fixed, CI can help immensely and be a huge learning aid to those contributing.

**Comment by MoonWolf125** [comment]
Yes, @KyleFiala and I were demonstrating what a student might expect in the workplace with a TMS, QA, UAT, and how that all coalesces with Git.

**Comment by alunduil** [comment]
Got it.  Then I'll unsubscribe.  It almost seems like you need to keep things like this only autosubscribed in a local group rather than a larger group.  Maybe create teams for students, alumni, and officers?  Then you can assign repositories to teams to keep some of the noise down so I don't start interjecting where it's less useful. ;)

**Pull request merged**
